
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: article_rk
  password: qwertq
  host: localhost
  port: 5432

development:
  <<: *default
  database: Article_development


test:
  <<: *default
  database: Article_test


production:
  <<: *default
  database: Article_production
  username: Article
  password: <%= ENV['ARTICLE_DATABASE_PASSWORD'] %>
